import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Bell, RotateCcw, PauseCircle, AlertTriangle, X, Eye, CheckCircle2, Clock, Hash } from "lucide-react";
import { PageHeader } from "../components/layout/PageHeader";
import { ChartCard } from "../components/dashboard/ChartCard";
import { FilterDropdown } from "../components/common/FilterDropdown";
import { LoadingSpinner } from "../components/common/LoadingSpinner";
import { ErrorState } from "../components/common/ErrorState";
import { useSlackNotifications } from "../hooks/useSlackNotifications";
import { formatDateTime } from "../utils/formatters";
import type { SlackNotification } from "../types/slack";

const SEVERITY_STYLES: Record<string, { bg: string; text: string; icon: any }> = {
  critical: { bg: "bg-error-50", text: "text-error", icon: RotateCcw },
  warning: { bg: "bg-warning-50", text: "text-warning", icon: AlertTriangle },
  info: { bg: "bg-primary-50", text: "text-primary", icon: Bell },
};

const ACTION_LABELS: Record<string, string> = {
  rollback: "Rollback",
  pause: "Pause",
  alert: "Alert",
  canary_passed: "Canary Passed",
  canary_failed: "Canary Failed",
  stage_advanced: "Stage Advanced",
  shadow_completed: "Shadow Completed",
};

const SEVERITY_OPTIONS = [
  { value: "all", label: "All Severities" },
  { value: "critical", label: "Critical" },
  { value: "warning", label: "Warning" },
  { value: "info", label: "Info" },
];

export default function SlackNotifications() {
  const { notifications, overview, loading, error, refetch } = useSlackNotifications();
  const [selected, setSelected] = useState<SlackNotification | null>(null);
  const [severity, setSeverity] = useState("all");

  if (loading || !overview) return <LoadingSpinner label="Loading notifications..." />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;

  const filtered = severity === "all" ? notifications : notifications.filter((n) => n.severity === severity);

  return (
    <div>
      <PageHeader
        title="Slack Notifications"
        description="Every notification generated by the AI rollout platform."
        actions={<FilterDropdown value={severity} options={SEVERITY_OPTIONS} onChange={setSeverity} />}
      />

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <div className="card p-4">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl2 bg-primary-50 text-primary">
            <Bell className="h-5 w-5" />
          </div>
          <p className="mt-3 font-display text-2xl font-semibold text-ink-900">{overview.totalAlerts}</p>
          <p className="text-sm text-ink-500">Total Alerts</p>
        </div>
        <div className="card p-4">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl2 bg-error-50 text-error">
            <RotateCcw className="h-5 w-5" />
          </div>
          <p className="mt-3 font-display text-2xl font-semibold text-ink-900">{overview.rollbackAlerts}</p>
          <p className="text-sm text-ink-500">Rollback Alerts</p>
        </div>
        <div className="card p-4">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl2 bg-warning-50 text-warning">
            <PauseCircle className="h-5 w-5" />
          </div>
          <p className="mt-3 font-display text-2xl font-semibold text-ink-900">{overview.pausedRollouts}</p>
          <p className="text-sm text-ink-500">Paused Rollouts</p>
        </div>
        <div className="card p-4">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl2 bg-warning-50 text-warning">
            <AlertTriangle className="h-5 w-5" />
          </div>
          <p className="mt-3 font-display text-2xl font-semibold text-ink-900">{overview.warnings}</p>
          <p className="text-sm text-ink-500">Warnings</p>
        </div>
      </div>

      <div className="mt-5">
        <ChartCard title="Notification Log" subtitle={`${filtered.length} events`}>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-ink-300/10 text-left text-xs font-medium text-ink-500">
                  <th className="pb-3 pr-4">Time</th>
                  <th className="pb-3 pr-4">Flag</th>
                  <th className="pb-3 pr-4">Severity</th>
                  <th className="pb-3 pr-4">Message</th>
                  <th className="pb-3 pr-4">Delivered</th>
                  <th className="pb-3 pr-4">Action</th>
                  <th className="pb-3" />
                </tr>
              </thead>
              <tbody>
                {filtered.map((n, i) => {
                  const SeverityIcon = SEVERITY_STYLES[n.severity].icon;
                  return (
                    <motion.tr
                      key={n.id}
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: i * 0.02 }}
                      className="cursor-pointer border-b border-ink-300/5 transition-colors hover:bg-surface-bg"
                      onClick={() => setSelected(n)}
                    >
                      <td className="py-3 pr-4 text-ink-500 whitespace-nowrap">{formatDateTime(n.timestamp)}</td>
                      <td className="py-3 pr-4 font-medium text-ink-900">{n.flagName}</td>
                      <td className="py-3 pr-4">
                        <span className={`inline-flex items-center gap-1 rounded-pill px-2 py-0.5 text-xs font-medium ${SEVERITY_STYLES[n.severity].bg} ${SEVERITY_STYLES[n.severity].text}`}>
                          <SeverityIcon className="h-3 w-3" />
                          {n.severity}
                        </span>
                      </td>
                      <td className="py-3 pr-4 max-w-[300px] truncate text-ink-700">{n.message}</td>
                      <td className="py-3 pr-4">
                        {n.delivered ? (
                          <span className="flex items-center gap-1 text-xs text-success">
                            <CheckCircle2 className="h-3.5 w-3.5" /> Yes
                          </span>
                        ) : (
                          <span className="text-xs text-error">No</span>
                        )}
                      </td>
                      <td className="py-3 pr-4">
                        <span className="text-xs font-medium text-ink-500">{ACTION_LABELS[n.action]}</span>
                      </td>
                      <td className="py-3">
                        <button className="focus-ring rounded-lg p-1.5 text-ink-500 hover:bg-black/5">
                          <Eye className="h-4 w-4" />
                        </button>
                      </td>
                    </motion.tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </ChartCard>
      </div>

      <AnimatePresence>
        {selected && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-start justify-center bg-ink-900/30 p-4 pt-12 backdrop-blur-sm"
            onClick={() => setSelected(null)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.96, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.96, y: 20 }}
              className="card w-full max-w-xl max-h-[80vh] overflow-y-auto p-6"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h3 className="font-display text-lg font-semibold text-ink-900">Notification Detail</h3>
                  <p className="text-sm text-ink-500">{selected.flagName}</p>
                </div>
                <button onClick={() => setSelected(null)} className="focus-ring rounded-lg p-2 text-ink-500 hover:bg-black/5">
                  <X className="h-5 w-5" />
                </button>
              </div>

              <div className="space-y-4">
                <div className="rounded-xl2 bg-surface-bg p-4">
                  <p className="text-xs font-semibold text-ink-500 mb-2">JSON Payload</p>
                  <pre className="text-xs text-ink-700 font-mono whitespace-pre-wrap">
                    {JSON.stringify(selected.jsonPayload, null, 2)}
                  </pre>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="rounded-xl2 bg-surface-bg p-4">
                    <p className="text-xs text-ink-500">Reason</p>
                    <p className="mt-1 text-sm text-ink-700">{selected.reason}</p>
                  </div>
                  <div className="rounded-xl2 bg-surface-bg p-4">
                    <p className="text-xs text-ink-500">Threshold</p>
                    <p className="mt-1 text-sm text-ink-700">{selected.threshold}</p>
                  </div>
                </div>

                <div className="rounded-xl2 bg-surface-bg p-4">
                  <p className="text-xs text-ink-500 mb-1">Current Metrics</p>
                  <p className="text-sm text-ink-700">{selected.currentMetrics}</p>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="rounded-xl2 bg-surface-bg p-4">
                    <p className="flex items-center gap-1.5 text-xs text-ink-500">
                      <Hash className="h-3 w-3" /> Slack Channel
                    </p>
                    <p className="mt-1 text-sm font-medium text-ink-700">{selected.channel}</p>
                  </div>
                  <div className="rounded-xl2 bg-surface-bg p-4">
                    <p className="flex items-center gap-1.5 text-xs text-ink-500">
                      <Clock className="h-3 w-3" /> Delivery Time
                    </p>
                    <p className="mt-1 text-sm font-medium text-ink-700">{selected.deliveryTimeMs}ms</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
